version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    gocognit:
      min-complexity: 20
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
      disable:
        - copylocks # disabled for simple diff check
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'S1039: unnecessary use of fmt.Sprintf' # complains if there is no URI arguments. Workaround is not worth it at the moment
      - linters:
          - govet
        text: 'fieldalignment:' # a minor flaw, won't fix
      - linters:
          - gocritic
        text: 'captLocal:' # doesn't seem to matter
      - linters:
          - gocritic
        text: 'singleCaseSwitch:' # complains if there is a single query argument
      - linters:
          - staticcheck
        text: 'SA9005:' # complains about empty structs
      - linters:
          - revive
        text: 'unused-parameter:' # generated named parameters
      - linters:
          - revive
        text: 'var-naming:' # build in param names
      - linters:
          - staticcheck
        text: 'ST1003:' # build in param names
      - linters:
          - staticcheck
        text: 'SA1029:' # string key types in generated code
      - linters:
          - gosec
        text: 'G115:' # skip overflow check
      - linters:
          - gosec
        text: 'G114: Use of net/http serve function that has no support for setting timeouts' # no need for example
      - linters:
          - revive
        text: 'context-keys-type:' # intensional use of string type
      - linters:
          - errcheck
        text: 'Error return value is not checked' # false positive, might be a linter bug
formatters:
  exclusions:
    generated: lax
