// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: somepackage/somepackage.proto

package somepackage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SomeCustomMsg1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeCustomMsg1) Reset() {
	*x = SomeCustomMsg1{}
	mi := &file_somepackage_somepackage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeCustomMsg1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeCustomMsg1) ProtoMessage() {}

func (x *SomeCustomMsg1) ProtoReflect() protoreflect.Message {
	mi := &file_somepackage_somepackage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeCustomMsg1.ProtoReflect.Descriptor instead.
func (*SomeCustomMsg1) Descriptor() ([]byte, []int) {
	return file_somepackage_somepackage_proto_rawDescGZIP(), []int{0}
}

func (x *SomeCustomMsg1) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SomeCustomMsg2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeCustomMsg2) Reset() {
	*x = SomeCustomMsg2{}
	mi := &file_somepackage_somepackage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeCustomMsg2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeCustomMsg2) ProtoMessage() {}

func (x *SomeCustomMsg2) ProtoReflect() protoreflect.Message {
	mi := &file_somepackage_somepackage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeCustomMsg2.ProtoReflect.Descriptor instead.
func (*SomeCustomMsg2) Descriptor() ([]byte, []int) {
	return file_somepackage_somepackage_proto_rawDescGZIP(), []int{1}
}

func (x *SomeCustomMsg2) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

var File_somepackage_somepackage_proto protoreflect.FileDescriptor

var file_somepackage_somepackage_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x73, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x6f,
	0x6d, 0x65, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x0e,
	0x73, 0x6f, 0x6d, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x31, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x22, 0x22, 0x0a, 0x0e, 0x73, 0x6f, 0x6d, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x73,
	0x67, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x61, 0x6c, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4d, 0x55, 0x6c, 0x74, 0x31, 0x6d, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x68, 0x74, 0x74, 0x70, 0x67, 0x6f, 0x2f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6f, 0x6d,
	0x65, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x3b, 0x73, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_somepackage_somepackage_proto_rawDescOnce sync.Once
	file_somepackage_somepackage_proto_rawDescData []byte
)

func file_somepackage_somepackage_proto_rawDescGZIP() []byte {
	file_somepackage_somepackage_proto_rawDescOnce.Do(func() {
		file_somepackage_somepackage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_somepackage_somepackage_proto_rawDesc), len(file_somepackage_somepackage_proto_rawDesc)))
	})
	return file_somepackage_somepackage_proto_rawDescData
}

var file_somepackage_somepackage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_somepackage_somepackage_proto_goTypes = []any{
	(*SomeCustomMsg1)(nil), // 0: somepackage.someCustomMsg1
	(*SomeCustomMsg2)(nil), // 1: somepackage.someCustomMsg2
}
var file_somepackage_somepackage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_somepackage_somepackage_proto_init() }
func file_somepackage_somepackage_proto_init() {
	if File_somepackage_somepackage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_somepackage_somepackage_proto_rawDesc), len(file_somepackage_somepackage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_somepackage_somepackage_proto_goTypes,
		DependencyIndexes: file_somepackage_somepackage_proto_depIdxs,
		MessageInfos:      file_somepackage_somepackage_proto_msgTypes,
	}.Build()
	File_somepackage_somepackage_proto = out.File
	file_somepackage_somepackage_proto_goTypes = nil
	file_somepackage_somepackage_proto_depIdxs = nil
}
