// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package proto

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (AllTypesMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*AllTypesMsg) UnmarshalJSON([]byte) error        { return nil }
func (AllTypesMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*AllTypesMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AllTypesMsg *AllTypesMsg

func (Array) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Array) UnmarshalJSON([]byte) error        { return nil }
func (Array) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Array) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Array *Array

func (ArrayItem) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ArrayItem) UnmarshalJSON([]byte) error        { return nil }
func (ArrayItem) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ArrayItem) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ArrayItem *ArrayItem

func (Empty) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Empty) UnmarshalJSON([]byte) error        { return nil }
func (Empty) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Empty) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Empty *Empty

func (InputMsgName) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*InputMsgName) UnmarshalJSON([]byte) error        { return nil }
func (InputMsgName) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*InputMsgName) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_InputMsgName *InputMsgName

func (OptionalField) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OptionalField) UnmarshalJSON([]byte) error        { return nil }
func (OptionalField) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OptionalField) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OptionalField *OptionalField

func (OutputMsgName) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OutputMsgName) UnmarshalJSON([]byte) error        { return nil }
func (OutputMsgName) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OutputMsgName) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OutputMsgName *OutputMsgName

func (RepeatedCheck) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*RepeatedCheck) UnmarshalJSON([]byte) error        { return nil }
func (RepeatedCheck) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*RepeatedCheck) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RepeatedCheck *RepeatedCheck
