// Code generated by protoc-gen-httpgo. DO NOT EDIT.
// source: proto/example.proto

package proto

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	fasthttp "github.com/valyala/fasthttp"
)

var _ ServiceNameHTTPService = &ServiceNameClient{}

type ServiceNameClient struct {
	cl   *fasthttp.Client
	host string
}

func GetServiceNameClient(_ context.Context, cl *fasthttp.Client, host string) (*ServiceNameClient, error) {
	return &ServiceNameClient{
		cl:   cl,
		host: host,
	}, nil
}

func (p *ServiceNameClient) RPCName(ctx context.Context, request *InputMsgName) (resp *OutputMsgName, err error) {
	body, _ := json.Marshal(request)
	req := &fasthttp.Request{}
	req.SetBody(body)
	req.SetRequestURI(p.host + fmt.Sprintf("/v1/test/%s/%d", request.StringArgument, request.Int64Argument))
	req.Header.SetMethod("POST")
	reqResp := &fasthttp.Response{}
	if err = p.cl.Do(req, reqResp); err != nil {
		return nil, err
	}
	resp = &OutputMsgName{}
	err = json.Unmarshal(reqResp.Body(), resp)
	return resp, err
}
