// Code generated by protoc-gen-httpgo. DO NOT EDIT.
// source: proto/no_url.proto

package proto

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	fmt "fmt"
	io "io"
	http "net/http"
	url "net/url"
)

type NoURLHTTPGoService interface {
	MethodWithoutURLAnnotation(context.Context, *Empty) (*Empty, error)
}

func RegisterNoURLHTTPGoServer(
	_ context.Context,
	r *http.ServeMux,
	h NoURLHTTPGoService,
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error),
) error {
	var middleware = chainServerMiddlewaresNourl(middlewares)

	r.HandleFunc("POST NoURL/MethodWithoutURLAnnotation", func(w http.ResponseWriter, r *http.Request) {
		input, err := buildNourlNoURLMethodWithoutURLAnnotationEmpty(r)
		if err != nil {
			w.WriteHeader(http.StatusBadRequest)
			_, _ = w.Write([]byte(err.Error()))
			return
		}
		ctx := r.Context()
		ctx = context.WithValue(ctx, "proto_service", "NoURL")
		ctx = context.WithValue(ctx, "proto_method", "MethodWithoutURLAnnotation")
		ctx = context.WithValue(ctx, "writer", w)
		ctx = context.WithValue(ctx, "request", r)
		handler := func(ctx context.Context, req interface{}) (resp interface{}, err error) {
			return h.MethodWithoutURLAnnotation(ctx, input)
		}
		if middleware == nil {
			_, _ = handler(ctx, input)
			return
		}
		_, _ = middleware(ctx, input, handler)
	})

	return nil
}

func buildNourlNoURLMethodWithoutURLAnnotationEmpty(r *http.Request) (arg *Empty, err error) {
	arg = &Empty{}
	var body []byte
	if body, err = io.ReadAll(r.Body); err != nil {
		return nil, err
	}
	_ = r.Body.Close()
	if len(body) > 0 {
		if err = json.Unmarshal(body, arg); err != nil {
			return nil, err
		}
	}
	return arg, err
}

func chainServerMiddlewaresNourl(
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error),
) func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error) {
	switch len(middlewares) {
	case 0:
		return nil
	case 1:
		return middlewares[0]
	default:
		return func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error) {
			return middlewares[0](ctx, req, getChainServerMiddlewareHandlerNourl(middlewares, 0, handler))
		}
	}
}

func getChainServerMiddlewareHandlerNourl(
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error),
	curr int,
	finalHandler func(ctx context.Context, req interface{}) (resp interface{}, err error),
) func(ctx context.Context, req interface{}) (resp interface{}, err error) {
	if curr == len(middlewares)-1 {
		return finalHandler
	}
	return func(ctx context.Context, req interface{}) (resp interface{}, err error) {
		return middlewares[curr+1](ctx, req, getChainServerMiddlewareHandlerNourl(middlewares, curr+1, finalHandler))
	}
}

var _ NoURLHTTPGoService = &NoURLHTTPGoClient{}

type NoURLHTTPGoClient struct {
	cl          *http.Client
	host        string
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error)
	middleware  func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error)
}

func GetNoURLHTTPGoClient(
	_ context.Context,
	cl *http.Client,
	host string,
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error),
) (*NoURLHTTPGoClient, error) {
	return &NoURLHTTPGoClient{
		cl:          cl,
		host:        host,
		middlewares: middlewares,
		middleware:  chainClientMiddlewaresNourl(middlewares),
	}, nil
}

func (p *NoURLHTTPGoClient) MethodWithoutURLAnnotation(ctx context.Context, request *Empty) (resp *Empty, err error) {
	req := &http.Request{Header: make(http.Header)}
	var queryArgs string
	var body []byte
	body, err = json.Marshal(request)
	if err != nil {
		return nil, err
	}
	req.Body = io.NopCloser(bytes.NewBuffer(body))
	u, err := url.Parse(fmt.Sprintf("%sNoURL/MethodWithoutURLAnnotation%s", p.host, queryArgs))
	if err != nil {
		return nil, err
	}
	req.URL = u
	req.Method = http.MethodPost
	var reqResp interface{}
	ctx = context.WithValue(ctx, "proto_service", "NoURL")
	ctx = context.WithValue(ctx, "proto_method", "MethodWithoutURLAnnotation")
	var handler = func(ctx context.Context, req interface{}) (resp interface{}, err error) {
		resp, err = p.cl.Do(req.(*http.Request))
		return resp, err
	}
	if p.middleware == nil {
		if reqResp, err = handler(ctx, req); err != nil {
			return nil, err
		}
	} else {
		if reqResp, err = p.middleware(ctx, req, handler); err != nil {
			return nil, err
		}
	}
	resp = &Empty{}
	var respBody []byte
	if respBody, err = io.ReadAll(reqResp.(*http.Response).Body); err != nil {
		return nil, err
	}
	_ = reqResp.(*http.Response).Body.Close()
	err = json.Unmarshal(respBody, resp)
	return resp, err
}

func chainClientMiddlewaresNourl(
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error),
) func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error) {
	switch len(middlewares) {
	case 0:
		return nil
	case 1:
		return middlewares[0]
	default:
		return func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error) {
			return middlewares[0](ctx, req, getChainClientMiddlewareHandlerNourl(middlewares, 0, handler))
		}
	}
}

func getChainClientMiddlewareHandlerNourl(
	middlewares []func(ctx context.Context, req interface{}, handler func(ctx context.Context, req interface{}) (resp interface{}, err error)) (resp interface{}, err error),
	curr int,
	finalHandler func(ctx context.Context, req interface{}) (resp interface{}, err error),
) func(ctx context.Context, req interface{}) (resp interface{}, err error) {
	if curr == len(middlewares)-1 {
		return finalHandler
	}
	return func(ctx context.Context, req interface{}) (resp interface{}, err error) {
		return middlewares[curr+1](ctx, req, getChainClientMiddlewareHandlerNourl(middlewares, curr+1, finalHandler))
	}
}
